var annotated_dup =
[
    [ "irio", "namespaceirio.html", [
      [ "bfp", "namespaceirio_1_1bfp.html", [
        [ "BFP", "classirio_1_1bfp_1_1BFP.html", "classirio_1_1bfp_1_1BFP" ],
        [ "DMA", "classirio_1_1bfp_1_1DMA.html", "classirio_1_1bfp_1_1DMA" ],
        [ "Register", "classirio_1_1bfp_1_1Register.html", "classirio_1_1bfp_1_1Register" ],
        [ "Resource", "classirio_1_1bfp_1_1Resource.html", "classirio_1_1bfp_1_1Resource" ]
      ] ],
      [ "errors", "namespaceirio_1_1errors.html", [
        [ "IrioError", "classirio_1_1errors_1_1IrioError.html", null ],
        [ "TerminalNotImplementedError", "classirio_1_1errors_1_1TerminalNotImplementedError.html", "classirio_1_1errors_1_1TerminalNotImplementedError" ],
        [ "ResourceNotFoundError", "classirio_1_1errors_1_1ResourceNotFoundError.html", "classirio_1_1errors_1_1ResourceNotFoundError" ],
        [ "FPGAVIVersionMismatchError", "classirio_1_1errors_1_1FPGAVIVersionMismatchError.html", "classirio_1_1errors_1_1FPGAVIVersionMismatchError" ],
        [ "UnsupportedPlatformError", "classirio_1_1errors_1_1UnsupportedPlatformError.html", "classirio_1_1errors_1_1UnsupportedPlatformError" ],
        [ "UnsupportedDevProfileError", "classirio_1_1errors_1_1UnsupportedDevProfileError.html", "classirio_1_1errors_1_1UnsupportedDevProfileError" ],
        [ "InitializationTimeoutError", "classirio_1_1errors_1_1InitializationTimeoutError.html", "classirio_1_1errors_1_1InitializationTimeoutError" ],
        [ "CLUARTTimeout", "classirio_1_1errors_1_1CLUARTTimeout.html", "classirio_1_1errors_1_1CLUARTTimeout" ],
        [ "CLUARTInvalidBaudRate", "classirio_1_1errors_1_1CLUARTInvalidBaudRate.html", "classirio_1_1errors_1_1CLUARTInvalidBaudRate" ],
        [ "ModulesNotOKError", "classirio_1_1errors_1_1ModulesNotOKError.html", null ],
        [ "RIODiscoveryError", "classirio_1_1errors_1_1RIODiscoveryError.html", null ],
        [ "RIODeviceNotFoundError", "classirio_1_1errors_1_1RIODeviceNotFoundError.html", "classirio_1_1errors_1_1RIODeviceNotFoundError" ],
        [ "NiFpgaError", "classirio_1_1errors_1_1NiFpgaError.html", null ],
        [ "NiFpgaErrorDownloadingBitfile", "classirio_1_1errors_1_1NiFpgaErrorDownloadingBitfile.html", null ],
        [ "NiFpgaFPGAAlreadyRunning", "classirio_1_1errors_1_1NiFpgaFPGAAlreadyRunning.html", null ],
        [ "DMAReadTimeout", "classirio_1_1errors_1_1DMAReadTimeout.html", "classirio_1_1errors_1_1DMAReadTimeout" ],
        [ "BFPParseBitfileError", "classirio_1_1errors_1_1BFPParseBitfileError.html", "classirio_1_1errors_1_1BFPParseBitfileError" ],
        [ "UnsupportedAICouplingForModule", "classirio_1_1errors_1_1UnsupportedAICouplingForModule.html", "classirio_1_1errors_1_1UnsupportedAICouplingForModule" ]
      ] ],
      [ "Irio", "classirio_1_1Irio.html", "classirio_1_1Irio" ],
      [ "ConfigParams", "structirio_1_1ConfigParams.html", "structirio_1_1ConfigParams" ],
      [ "Module", "classirio_1_1Module.html", "classirio_1_1Module" ],
      [ "ModuleNI5761", "classirio_1_1ModuleNI5761.html", "classirio_1_1ModuleNI5761" ],
      [ "ModuleNI6581", "classirio_1_1ModuleNI6581.html", "classirio_1_1ModuleNI6581" ],
      [ "ModuleNI5734", "classirio_1_1ModuleNI5734.html", "classirio_1_1ModuleNI5734" ],
      [ "ModuleNI5781", "classirio_1_1ModuleNI5781.html", "classirio_1_1ModuleNI5781" ],
      [ "ModuleNI92xx", "classirio_1_1ModuleNI92xx.html", "classirio_1_1ModuleNI92xx" ],
      [ "ResourceError", "structirio_1_1ResourceError.html", "structirio_1_1ResourceError" ],
      [ "ResourceErrorHash", "structirio_1_1ResourceErrorHash.html", "structirio_1_1ResourceErrorHash" ],
      [ "CustomStringComparator", "structirio_1_1CustomStringComparator.html", "structirio_1_1CustomStringComparator" ],
      [ "GroupInfo", "structirio_1_1GroupInfo.html", "structirio_1_1GroupInfo" ],
      [ "ParserManager", "classirio_1_1ParserManager.html", "classirio_1_1ParserManager" ],
      [ "Platform", "classirio_1_1Platform.html", "classirio_1_1Platform" ],
      [ "PlatformFlexRIO", "classirio_1_1PlatformFlexRIO.html", "classirio_1_1PlatformFlexRIO" ],
      [ "PlatformCRIO", "classirio_1_1PlatformCRIO.html", "classirio_1_1PlatformCRIO" ],
      [ "PlatformRSeries", "classirio_1_1PlatformRSeries.html", "classirio_1_1PlatformRSeries" ],
      [ "ProfileBase", "classirio_1_1ProfileBase.html", "classirio_1_1ProfileBase" ],
      [ "ProfileCPUDAQ", "classirio_1_1ProfileCPUDAQ.html", "classirio_1_1ProfileCPUDAQ" ],
      [ "ProfileCPUDAQcRIO", "classirio_1_1ProfileCPUDAQcRIO.html", "classirio_1_1ProfileCPUDAQcRIO" ],
      [ "ProfileCPUDAQFlexRIO", "classirio_1_1ProfileCPUDAQFlexRIO.html", "classirio_1_1ProfileCPUDAQFlexRIO" ],
      [ "ProfileCPUIMAQ", "classirio_1_1ProfileCPUIMAQ.html", "classirio_1_1ProfileCPUIMAQ" ],
      [ "ProfileCPUIMAQFlexRIO", "classirio_1_1ProfileCPUIMAQFlexRIO.html", "classirio_1_1ProfileCPUIMAQFlexRIO" ],
      [ "ProfileCRIO", "classirio_1_1ProfileCRIO.html", "classirio_1_1ProfileCRIO" ],
      [ "ProfileFlexRIO", "classirio_1_1ProfileFlexRIO.html", "classirio_1_1ProfileFlexRIO" ],
      [ "TerminalsAnalog", "classirio_1_1TerminalsAnalog.html", "classirio_1_1TerminalsAnalog" ],
      [ "TerminalsAuxAnalog", "classirio_1_1TerminalsAuxAnalog.html", "classirio_1_1TerminalsAuxAnalog" ],
      [ "TerminalsAuxDigital", "classirio_1_1TerminalsAuxDigital.html", "classirio_1_1TerminalsAuxDigital" ],
      [ "TerminalsBase", "classirio_1_1TerminalsBase.html", "classirio_1_1TerminalsBase" ],
      [ "TerminalscRIO", "classirio_1_1TerminalscRIO.html", "classirio_1_1TerminalscRIO" ],
      [ "TerminalsDigital", "classirio_1_1TerminalsDigital.html", "classirio_1_1TerminalsDigital" ],
      [ "TerminalsDMACommon", "classirio_1_1TerminalsDMACommon.html", "classirio_1_1TerminalsDMACommon" ],
      [ "TerminalsDMADAQ", "classirio_1_1TerminalsDMADAQ.html", "classirio_1_1TerminalsDMADAQ" ],
      [ "TerminalsDMADAQCPU", "classirio_1_1TerminalsDMADAQCPU.html", "classirio_1_1TerminalsDMADAQCPU" ],
      [ "TerminalsDMAIMAQ", "classirio_1_1TerminalsDMAIMAQ.html", "classirio_1_1TerminalsDMAIMAQ" ],
      [ "TerminalsDMAIMAQCPU", "classirio_1_1TerminalsDMAIMAQCPU.html", "classirio_1_1TerminalsDMAIMAQCPU" ],
      [ "TerminalsFlexRIO", "classirio_1_1TerminalsFlexRIO.html", "classirio_1_1TerminalsFlexRIO" ],
      [ "TerminalsSignalGeneration", "classirio_1_1TerminalsSignalGeneration.html", "classirio_1_1TerminalsSignalGeneration" ]
    ] ]
];