var files_dup =
[
    [ "bfp.h", "bfp_8h.html", null ],
    [ "dma.h", "dma_8h.html", null ],
    [ "elemtypes.h", "elemtypes_8h.html", "elemtypes_8h" ],
    [ "errorsIrio.h", "errorsIrio_8h.html", null ],
    [ "fpgatypes.h", "fpgatypes_8h.html", "fpgatypes_8h" ],
    [ "frameTypes.h", "frameTypes_8h.html", "frameTypes_8h" ],
    [ "imaqTypes.h", "imaqTypes_8h.html", "imaqTypes_8h" ],
    [ "irioCoreCpp.h", "irioCoreCpp_8h.html", "irioCoreCpp_8h" ],
    [ "modules.h", "modules_8h.html", "modules_8h" ],
    [ "namesTerminalsAnalog.h", "namesTerminalsAnalog_8h.html", "namesTerminalsAnalog_8h" ],
    [ "namesTerminalsAuxAnalog.h", "namesTerminalsAuxAnalog_8h.html", "namesTerminalsAuxAnalog_8h" ],
    [ "namesTerminalsAuxDigital.h", "namesTerminalsAuxDigital_8h.html", "namesTerminalsAuxDigital_8h" ],
    [ "namesTerminalsCommon.h", "namesTerminalsCommon_8h.html", "namesTerminalsCommon_8h" ],
    [ "namesTerminalsCRIO.h", "namesTerminalsCRIO_8h.html", "namesTerminalsCRIO_8h" ],
    [ "namesTerminalsDigital.h", "namesTerminalsDigital_8h.html", "namesTerminalsDigital_8h" ],
    [ "namesTerminalsDMACPUCommon.h", "namesTerminalsDMACPUCommon_8h.html", "namesTerminalsDMACPUCommon_8h" ],
    [ "namesTerminalsDMADAQCPU.h", "namesTerminalsDMADAQCPU_8h.html", "namesTerminalsDMADAQCPU_8h" ],
    [ "namesTerminalsDMADAQGPU.h", "namesTerminalsDMADAQGPU_8h.html", "namesTerminalsDMADAQGPU_8h" ],
    [ "namesTerminalsDMAGPUCommon.h", "namesTerminalsDMAGPUCommon_8h.html", "namesTerminalsDMAGPUCommon_8h" ],
    [ "namesTerminalsDMAIMAQ.h", "namesTerminalsDMAIMAQ_8h.html", "namesTerminalsDMAIMAQ_8h" ],
    [ "namesTerminalsFlexRIO.h", "namesTerminalsFlexRIO_8h.html", "namesTerminalsFlexRIO_8h" ],
    [ "namesTerminalsIO.h", "namesTerminalsIO_8h.html", "namesTerminalsIO_8h" ],
    [ "namesTerminalsSignalGeneration.h", "namesTerminalsSignalGeneration_8h.html", "namesTerminalsSignalGeneration_8h" ],
    [ "parserManager.h", "parserManager_8h.html", "parserManager_8h" ],
    [ "platforms.h", "platforms_8h.html", "platforms_8h" ],
    [ "profileBase.h", "profileBase_8h.html", null ],
    [ "profileCPUDAQ.h", "profileCPUDAQ_8h.html", null ],
    [ "profileCPUDAQcRIO.h", "profileCPUDAQcRIO_8h.html", null ],
    [ "profileCPUDAQFlexRIO.h", "profileCPUDAQFlexRIO_8h.html", null ],
    [ "profileCPUIMAQ.h", "profileCPUIMAQ_8h.html", [
      [ "ProfileCPUIMAQ", "classirio_1_1ProfileCPUIMAQ.html", "classirio_1_1ProfileCPUIMAQ" ]
    ] ],
    [ "profileCPUIMAQFlexRIO.h", "profileCPUIMAQFlexRIO_8h.html", [
      [ "ProfileCPUIMAQFlexRIO", "classirio_1_1ProfileCPUIMAQFlexRIO.html", "classirio_1_1ProfileCPUIMAQFlexRIO" ]
    ] ],
    [ "profileCRIO.h", "profileCRIO_8h.html", null ],
    [ "profileFlexRIO.h", "profileFlexRIO_8h.html", null ],
    [ "profiles.h", "profiles_8h.html", null ],
    [ "profilesTypes.h", "profilesTypes_8h.html", "profilesTypes_8h" ],
    [ "register.h", "register_8h.html", null ],
    [ "resource.h", "resource_8h.html", null ],
    [ "rioDiscovery.h", "rioDiscovery_8h.html", "rioDiscovery_8h" ],
    [ "terminals.h", "terminals_8h.html", null ],
    [ "terminalsAnalog.h", "terminalsAnalog_8h.html", null ],
    [ "terminalsAuxAnalog.h", "terminalsAuxAnalog_8h.html", null ],
    [ "terminalsAuxDigital.h", "terminalsAuxDigital_8h.html", null ],
    [ "terminalsBase.h", "terminalsBase_8h.html", "terminalsBase_8h" ],
    [ "terminalsCRIO.h", "terminalsCRIO_8h.html", null ],
    [ "terminalsDigital.h", "terminalsDigital_8h.html", null ],
    [ "terminalsDMACommon.h", "terminalsDMACommon_8h.html", null ],
    [ "terminalsDMADAQ.h", "terminalsDMADAQ_8h.html", null ],
    [ "terminalsDMADAQCPU.h", "terminalsDMADAQCPU_8h.html", null ],
    [ "terminalsDMAIMAQ.h", "terminalsDMAIMAQ_8h.html", null ],
    [ "terminalsDMAIMAQCPU.h", "terminalsDMAIMAQCPU_8h.html", null ],
    [ "terminalsFlexRIO.h", "terminalsFlexRIO_8h.html", null ],
    [ "terminalsSignalGeneration.h", "terminalsSignalGeneration_8h.html", null ],
    [ "utils.h", "utils_8h.html", "utils_8h" ]
];