#pragma once

#define TERMINAL_DMATTOGPUNCH "DMATtoGPUNCh"
#define TERMINAL_DMATTOGPUFRAMETYPE "DMATtoGPUFrameType"
#define TERMINAL_DMATTOGPUSAMPLESIZE "DMATtoGPUSampleSize"
#define TERMINAL_DMATTOGPU "DMATtoGPU"
#define TERMINAL_DMATTOGPUENABLE "DMATtoGPUEnable"
#define TERMINAL_DMATTOGPUOVERFLOWS "DMATtoGPUOverflows"