#pragma once

#define TERMINAL_DMATTOHOSTNCH "DMATtoHOSTNCh"
#define TERMINAL_DMATTOHOSTFRAMETYPE "DMATtoHOSTFrameType"
#define TERMINAL_DMATTOHOSTSAMPLESIZE "DMATtoHOSTSampleSize"
#define TERMINAL_DMATTOHOST "DMATtoHOST"
#define TERMINAL_DMATTOHOSTENABLE "DMATtoHOSTEnable"
#define TERMINAL_DMATTOHOSTOVERFLOWS "DMATtoHOSTOverflows"