#pragma once

#define TERMINAL_SIGNALMAPPING "SignalMapping"
#define TERMINAL_CONFIGURATION "Configuration"
#define TERMINAL_LINESCAN "LineScan"
#define TERMINAL_FVALHIGH "FVALHigh"
#define TERMINAL_LVALHIGH "LVALHigh"
#define TERMINAL_DVALHIGH "DVALHigh"
#define TERMINAL_SPAREHIGH "SpareHigh"
#define TERMINAL_CONTROLENABLE "ControlEnable"
#define TERMINAL_UARTTRANSMIT "uartTransmit"
#define TERMINAL_UARTRECEIVE "uartReceive"
#define TERMINAL_UARTSETBAUDRATE "uartSetBaudRate"
#define TERMINAL_UARTBAUDRATE "uartBaudRate"
#define TERMINAL_UARTBYTEMODE "uartByteMode"
#define TERMINAL_UARTTXBYTE "uartTxByte"
#define TERMINAL_UARTRXBYTEA "uartRxBytea"
#define TERMINAL_UARTTXREADY "uartTxReady"
#define TERMINAL_UARTRXREADY "uartRxReady"
#define TERMINAL_UARTBREAKINDICATOR "uartBreakIndicator"
#define TERMINAL_UARTFRAMMINGERROR "uartFrammingError"
#define TERMINAL_UARTOVERRUNERROR "uartOverrunError"