name: doc

on: 
  workflow_call:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  generate_doc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: sudo apt install -y doxygen graphviz

      - name: Generate Documentation
        run: make doc
      
      - name: Extract Project Name
        id: extract_project_name
        run: echo "PROJECT_NAME=$(echo $GITHUB_REPOSITORY | cut -d / -f 2)" >> $GITHUB_OUTPUT

      - name: Upload doc artifact
        uses: actions/upload-artifact@v4
        with:
          name: doc_${{ steps.extract_project_name.outputs.PROJECT_NAME }}_${{ github.sha }}
          path: ./target/doc/${{ steps.extract_project_name.outputs.PROJECT_NAME }}/html
